# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TTT-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TTT-iOS
  pod 'Charts'
  pod 'lottie-ios' 

  # Network
  pod 'Moya/RxSwift'

end
